name: prepare ak3
description: copy kernel image to ak3 folder
inputs:
 branch:
  description: 'device kernel/repo'
  required: true

runs:
 using: composite
 steps:
  - name: add kernel checking to script
    shell: bash
    run: |
     cd "$ANYKERNEL3"

     sed -i 's/do.check_boot_version=.*/do.check_boot_version=1/' anykernel.sh
     
  - name: copy image to ak3 folder depending on branch
    shell: bash
    run: |
     cd "$CONFIG"

     if [[ -f ./kernel_platform/bazel-bin/common/kernel_aarch64/Image ]]; then
       cp ./kernel_platform/bazel-bin/common/kernel_aarch64/Image "$ANYKERNEL3/Image"
     elif [[ -f ./bazel-bin/kernel/kernel_aarch64/Image ]]; then
     cp ./bazel-bin/kernel/kernel_aarch64/Image "$ANYKERNEL3/Image"
     elif [[ "${{ inputs.branch }}" == "SM-S928B-Oneui7" || "${{ inputs.branch }}" == "SM-S928B-Oneui8-bit4" || "${{ inputs.branch }}" == "SM-S928B-Oneui8-bit5" || "${{ inputs.branch }}" == "SM-F741B-Oneui8" ]]; then
       cp ./kernel_platform/sec/dist/Image "$ANYKERNEL3/Image"
     elif [[ "${{ inputs.branch }}" == "SM-S928B-Oneui6.1" ]]; then
       cp ./out/msm-pineapple-pineapple-gki/dist/Image "$ANYKERNEL3/Image"
     elif [[ "${{ inputs.branch }}" == "SM-S938B-Oneui7" || "${{ inputs.branch }}" == "SM-S931B-Oneui8" || "${{ inputs.branch }}" == "SM-M556B-Oneui8" ]]; then
       cp ./kernel_platform/gki/dist/Image "$ANYKERNEL3/Image"
     elif [[ "${{ inputs.branch }}" == "SM-X916B" || "${{ inputs.branch }}" == "SM-F946N-Oneui7" || "${{ inputs.branch }}" == "SM-F946B-Oneui8" || "${{ inputs.branch }}" == "SM-S916B-Oneui8" || "${{ inputs.branch }}" == "SM-S918B-Oneui8" || ${{ inputs.branch }} == SM-S911B* || "${{ inputs.branch }}" == "SM-X710-Oneui6.1.1" ]]; then
       cp ./out/msm-kalama-kalama-gki/dist/Image "$ANYKERNEL3/Image"
     elif [[ ${{ inputs.branch }} == SM-A546* || "${{ inputs.branch }}" == "SM-M146B-Oneui7-ADYJ2" || "${{ inputs.branch }}" == "SM-S908B-Oneui8-bitK" || "${{ inputs.branch }}" == "SM-X610-Oneui6.1.1-bit7" || "${{ inputs.branch }}" == "SM-A166B-Oneui7" ]]; then
       cp ./arch/arm64/boot/Image "$ANYKERNEL3/Image"
     elif [[ "${{ inputs.branch }}" == "SM-A566B" ]]; then
       cp ./kernel-6.6/out/arch/arm64/boot/Image "$ANYKERNEL3/Image"
     elif [[ ${{ inputs.branch }} == SM-S926B* ]]; then
       cp ./out/s5e9945_user/dist/Image "$ANYKERNEL3/Image"
     elif [[ ${{ inputs.branch }} == SM-A556* ]]; then
       cp ./out/s5e8845_user/dist/Image "$ANYKERNEL3/Image"
     elif [[ "${{ inputs.branch }}" == "SM-S901E-Oneui8" || "${{ inputs.branch }}" == "SM-X800-Oneui8" ]]; then
       cp ./out/msm-waipio-waipio-gki/dist/Image "$ANYKERNEL3/Image"
     elif [[ ${{ inputs.branch }} == SM-A055* ]]; then
       cp ./out/target/product/a05m/obj/KLEAF_OBJ/dist/kernel_device_modules-6.6/mgk_64_k66_kernel_aarch64.user/Image.gz "$ANYKERNEL3/Image.gz"
     elif [[ "${{ inputs.branch }}" == "SM-A075M-Oneui7" ]]; then
       cp ./out/target/product/a07/obj/KERNEL_OBJ/kernel-5.10/arch/arm64/boot/Image.gz "$ANYKERNEL3/Image.gz"
     elif [[ ${{ inputs.branch }} == SM-X926* ]]; then
       cp ./out/target/product/gts10u/obj/KLEAF_OBJ/dist/kernel_device_modules-6.1/mgk_64_k61_kernel_aarch64.user/Image.gz "$ANYKERNEL3/Image.gz"
     else
       echo "Error: Image file not found in any expected location"
       exit 1
     fi
