name: set file name for ak3zip
description: set file name for ak3 zip
inputs:
 branch:
  description: 'Device kernel'
  required: true
 android_version:
  description: 'Android version (android14)'
  required: true
 kernel_version:
  description: 'Kernel version (6.1)'
  required: true
 ksun:
  description: 'ksun'
  required: true
 susfs:
  description: 'susfs'
  required: true
 zeromount:
  description: 'zeromount'
  required: true
 bbg:
  description: 'bbg'
  required: true
 bbrv1:
  description: 'bbrv1'
  required: true
 bbrv3:
  description: 'bbrv3'
  required: true
 droidspaces:
  description: 'droidspaces'
  required: true
 ntsync:
  description: 'ntsync'
  required: true
 ipv6_nat:
  description: 'ipv6_nat and IP-Set'
  required: true
 ttl:
  description: 'ttl'
  required: true
 unicodefix:
  description: 'unicode fix'
  required: true

runs:
 using: composite
 steps:
  - name: set file name for ak3zip
    shell: bash
    run: |
     ARTIFACT_BASE="${{ inputs.branch }}"
          
     # This gives dynamic file name depending on which features are enabled
     FILE_NAME="${ARTIFACT_BASE}"
     [[ "${{ inputs.ksun }}" == "true" ]] && FILE_NAME="${FILE_NAME}-KSUN${KSU_VERSION}"
     [[ "${{ inputs.susfs }}" == "true" ]] && FILE_NAME="${FILE_NAME}-SUSFS"
     [[ "${{ inputs.zeromount }}" == "true" ]] && FILE_NAME="${FILE_NAME}-ZM"
     [[ "${{ inputs.bbg }}" == "true" ]] && FILE_NAME="${FILE_NAME}-BBG"
     [[ "${{ inputs.bbrv1 }}" == "true" ]] && FILE_NAME="${FILE_NAME}-BBRV1"
     [[ "${{ inputs.bbrv3 }}" == "true" ]] && FILE_NAME="${FILE_NAME}-BBRV3"
     [[ "${{ inputs.droidspaces }}" == "true" ]] && FILE_NAME="${FILE_NAME}-DS"
     [[ "${{ inputs.ntsync }}" == "true" ]] && FILE_NAME="${FILE_NAME}-NTS"
     [[ "${{ inputs.ipv6_nat }}" == "true" ]] && FILE_NAME="${FILE_NAME}-IPv6_IP-set"
     [[ "${{ inputs.ttl }}" == "true" ]] && FILE_NAME="${FILE_NAME}-TTL"
     [[ "${{ inputs.unicodefix }}" == "true" ]] && FILE_NAME="${FILE_NAME}-UF"
     
      
     echo "ARTIFACT_BASE=$ARTIFACT_BASE" >> $GITHUB_ENV
     echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
          
     echo "✅ Final artifact name: $FILE_NAME"
