name: change clang variables to ccache clang
description: change clang cariable to ccache clang

runs:
 using: composite
 steps:
  - name: change variables
    shell: bash
    run: |
      cd "$CONFIG"
      if [[ -d kernel_platform ]]; then
      cd kernel_platform
      touch .bazelrc
      cat >> .bazelrc << 'EOF'
      #build --disk_cache=${{ env.BCACHE_DIR }}
      build --sandbox_writable_path=${{ env.CCACHE_DIR }}
      build --action_env=CC="ccache clang"
      build --action_env=CXX="ccache clang++"
      build --action_env=HOSTCC="ccache clang"
      build --action_env=HOSTCXX="ccache clang++"
      EOF
      else
      touch .bazelrc
      cat >> .bazelrc << 'EOF'
      #build --disk_cache=${{ env.BCACHE_DIR }}
      build --sandbox_writable_path=${{ env.CCACHE_DIR }}
      build --action_env=CC="ccache clang"
      build --action_env=CXX="ccache clang++"
      build --action_env=HOSTCC="ccache clang"
      build --action_env=HOSTCXX="ccache clang++"
      EOF
      fi
