name: change clang variables to ccache clang
description: change clang cariable to ccache clang

runs:
 using: composite
 steps:
  - name: change variables
    shell: bash
    run: |
      cd "$CONFIG"
      if [[ -f kernel_platform/build/kernel/build.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        kernel_platform/build/kernel/build.sh
      elif [[ -f kernel_platform/build/kernel/_setup_env.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        kernel_platform/build/kernel/_setup_env.sh
      elif [[ -f /build/kernel/build.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        build/kernel/build.sh
      elif [[-f build/kernel/_setup_env.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        build/kernel/_setup_env.sh
      elif [[-f kernel/build/kernel/build.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        kernel/build/kernel/build.sh
      elif [[-f kernel/build/kernel/_setup_env.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        kernel/build/kernel/_setup_env.sh
      elif [[-f build/kernel/build.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        kernel/build/kernel/build.sh
      elif [[-f build/kernel/_setup_env.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        kernel/build/kernel/_setup_env.sh
      else
        sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        Makefile
      fi
