name: add droidspaces
description: apply patches and configs for droidspaces support
inputs:
 kernel_version:
  description: 'Kernel version (5.10)'
  required: true

runs:
 using: composite
 steps:
  - name: apply patch and add configs
    shell: bash
    run: |
     cd "$COMMON"
     # ABI: use ABI padding for SYSVIPC This commit allows us to enable CONFIG_SYSVIPC in defconfig without breaking kernel ABI
     patch -p1 < "$KERNEL_PATCHES/common/droidspaces/fix_sysvipc_kabi_6_7_8.patch"

     if [[ "${{ inputs.kernel_version }}" == "5.10" ]]; then
      patch -p1 < "$KERNEL_PATCHES/common/droidspaces/fix_abi_padding_for_posix_mqueue.patch"
     fi

     cd "$GITHUB_WORKSPACE"
     cat >> "$GKI_DEFCONFIG" << 'EOF'
     # IPC
     CONFIG_SYSVIPC=y
     CONFIG_POSIX_MQUEUE=y

     # Namespaces
     CONFIG_IPC_NS=y
     CONFIG_PID_NS=y

     # HW Access Support
     CONFIG_DEVTMPFS=y

     # Below configs are optional

     # Docker NAT
     CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y

     # UFW
     CONFIG_NETFILTER_XT_TARGET_REJECT=y
     CONFIG_NETFILTER_XT_TARGET_LOG=y
     CONFIG_NETFILTER_XT_MATCH_RECENT=y

     # Fail2Ban
     CONFIG_IP_SET=y
     CONFIG_IP_SET_HASH_IP=y
     CONFIG_IP_SET_HASH_NET=y
     CONFIG_NETFILTER_XT_SET=y
     EOF
