name: add kernel optimizations
description: apply patches from kernel patches repo for kernel optimization

runs:
 using: composite
 steps:
  - name: apply patches
    shell: bash
    run: |
     cd "$COMMON"

     # CAUSES COMPILE ERROR-p1 -F 3 < "$KERNEL_PATCHES/common/add_limitation_scaling_min_freq.patch"
     patch -p1 -F 3 < "$KERNEL_PATCHES/common/add_timeout_wakelocks_globally.patch"
     patch -p1 -F 3 < "$KERNEL_PATCHES/common/adjust_cpu_scan_order.patch"
     # PATCH FAILS ON ONEUI 8.5patch -p1 -F 3 < "$KERNEL_PATCHES/common/avoid_extra_s2idle_wake_attempts.patch"
     patch -p1 -F 3 < "$KERNEL_PATCHES/common/clear_page_16bytes_align.patch"
