name: clone dependencies
description: dependencies
inputs:
 android_version:
    description: 'Android version (e.g., android15)'
    required: true
 kernel_version:
    description: 'Kernel version (e.g., 6.6)'
    required: true
 zeromount:
    description: 'zeromount'
    required: true
 susfs:
    description: 'SUSFS'
    required: true

runs:
 using: composite
 steps:
  - name: clone susfs and change commit if necessary, and clone kernel patches
    shell: bash
    run: |
     ANYKERNEL_BRANCH="gki-2.0"
     git clone https://github.com/WildKernels/kernel_patches.git
     git clone https://github.com/WildKernels/AnyKernel3.git -b "$ANYKERNEL_BRANCH"
     if [[ ${{ inputs.zeromount }} == 'true' ]]; then
      git clone https://github.com/jimsterino98/Super-Builders.git
     fi

     if [[ ${{ inputs.susfs }} == 'true' ]]; then
      SUSFS_BRANCH="gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}"
      git clone https://gitlab.com/simonpunk/susfs4ksu.git -b "$SUSFS_BRANCH"
     
      cd susfs4ksu
      if [[ "${{ inputs.android_version }}-${{ inputs.kernel_version }}" == "android12-5.10" ]]; then
        COMMIT=ce2c2b2dea28c89d33f61af898cc18a93bf65ae9
      elif [[ "${{ inputs.android_version }}-${{ inputs.kernel_version }}" == "android13-5.15" ]]; then
        COMMIT=529919fbc9f8aee6ee70eb3a8890ef33af0a109c
      elif [[ "${{ inputs.android_version }}-${{ inputs.kernel_version }}" == "android14-6.1" ]]; then
        COMMIT=d1327b62e0854603cfc26e2226e0a993ec9b0656
      elif [[ "${{ inputs.android_version }}-${{ inputs.kernel_version }}" == "android15-6.6" ]]; then
        COMMIT=676d202ed2cc322a2f90bcb2b56bc4f6a864acb8
      fi
      git checkout "$COMMIT"
     fi
