name: change clang variables to ccache clang
description: change clang cariable to ccache clang
inputs:
  branch:
   description: 'device kernel'
   required: true

runs:
 using: composite
 steps:
  - name: change variables
    shell: bash
    run: |
      
      if [[ -f ${{ inputs.branch }}/kernel_platform/build/kernel/build.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        ${{ inputs.branch }}/kernel_platform/build/kernel/build.sh \
        "$COMMON/Makefile"
      elif [[ -f ${{ inputs.branch }}/kernel_platform/build/kernel/_setup_env.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        ${{ inputs.branch }}/kernel_platform/build/kernel/_setup_env.sh \
        "$COMMON/Makefile"
      elif [[ -f ${{ inputs.branch }}/kernel_platform/build/build.sh ]]; then
        sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        ${{ inputs.branch }}/kernel_platform/build/build.sh \
        "$COMMON/Makefile"
      elif [[ -f ${{ inputs.branch }}/kernel_platform/build/_setup_env.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        ${{ inputs.branch }}/kernel_platform/build/_setup_env.sh \
        "$COMMON/Makefile"
      elif [[ -f ${{ inputs.branch }}/build/kernel/build.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        ${{ inputs.branch }}/build/kernel/build.sh \
        "$COMMON/Makefile"
      elif [[ -f ${{ inputs.branch }}/build/kernel/_setup_env.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        ${{ inputs.branch }}/build/kernel/_setup_env.sh \
        "$COMMON/Makefile"
      elif [[ -f ${{ inputs.branch }}/kernel/build/kernel/build.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        ${{ inputs.branch }}/kernel/build/kernel/build.sh \
        "$COMMON/Makefile"
      elif [[ -f ${{ inputs.branch }}/kernel/build/kernel/_setup_env.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        ${{ inputs.branch }}/kernel/build/kernel/_setup_env.sh \
        "$COMMON/Makefile"
      elif [[ -f ${{ inputs.branch }}/build/kernel/build.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        ${{ inputs.branch }}/build/kernel/build.sh \
        "$COMMON/Makefile"
      elif [[ -f ${{ inputs.branch }}/build/kernel/_setup_env.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        ${{ inputs.branch }}/build/kernel/_setup_env.sh \
        "$COMMON/Makefile"
      elif [[ -f ${{ inputs.branch }}/kernel/build/build.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        ${{ inputs.branch }}/kernel/build/build.sh \
        "$COMMON/Makefile"
      elif [[ -f ${{ inputs.branch }}/kernel/build/_setup_env.sh ]]; then
       sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        ${{ inputs.branch }}/kernel/build/_setup_env.sh \
        "$COMMON/Makefile"
      else
        sed -i -E \
        -e 's/^CC[[:space:]]*[:?+]?=.*/CC = ccache clang/' \
        -e 's/^CXX[[:space:]]*[:?+]?=.*/CXX = ccache clang++/' \
        -e 's/^HOSTCC[[:space:]]*[:?+]?=.*/HOSTCC = ccache clang/' \
        -e 's/^HOSTCXX[[:space:]]*[:?+]?=.*/HOSTCXX = ccache clang++/' \
        ${{ inputs.branch }}/Makefile
      fi
